layout_spectrum: 0.7115496531925579
typography_spectrum: 0.05295335418858225
color:
  brandStrength: 0.9897794821278404
  lightness: 0.7906949634862935
  saturation: 0.7344685472932524
  rhythmicContrast: 0.2739475103955495
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
github: true
opengraph:
  appId: sheungggggg
author:
  name: Sheung
  email: psychesholia@gmail.com
  url: 'http://facebook.com/psychesholia'
logo: null
name: psychesholia
navigation:
  - name: facebook
    url: 'http://facebook.com/psychesholia'
    type: external
  - name: instagram
    url: 'http://instagram.com/psychesholia_'
    type: external
title: psychesholia
content: []
description: the earth has music for those who listen
