layout_spectrum: 0.9455282168818803
typography_spectrum: 0.2918669023492032
color:
  brandStrength: 0.729486978034498
  lightness: 0.09325578222014379
  saturation: 0.8118529047046116
  rhythmicContrast: 0.2321544340675199
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
github: true
opengraph:
  appId: sheungggggg
author:
  name: Sheung
  email: psychesholia@gmail.com
  url: 'http://facebook.com/psychesholia'
logo: null
name: psychesholia
navigation:
  - name: facebook
    url: 'http://facebook.com/psychesholia'
    type: external
  - name: instagram
    url: 'http://instagram.com/psychesholia_'
    type: external
title: psychesholia
content: []
description: the earth has music for those who listen
